[package]
name = "ap"
version = "0.1.0"
authors = ["Daniele Falchetti <danielefalche@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.6.1", features = ["router", "fullstack"] }

[features]
default = ["web"]
web = ["dioxus/web"]
mobile = ["dioxus/mobile"]
desktop = ["dioxus/desktop"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
