[package]
name = "ap"
version = "1.4.7"
edition = "2021"
description = "ap"
authors = ["Daniele Falchetti <danielefalche@gmail.com>"]
license = "MIT"
repository = "https://github.com/falcosan/ap"

[dependencies]
axum = "0.8"
minijinja = "2"
dotenv = "0.15.0"
serde_json = "1.0.138"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
tower-http = { version = "0.6.2", features = ["fs"] }
serde = { version = "1.0.217", features = ["derive"] }

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
panic = "abort"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz"]
