[build]
command = "curl -L https://dioxuslabs.com/install.sh | sh && dx bundle --platform web --release"
publish = "dist"
base = "/"

[build.environment]
RUST_VERSION = "1.83"
CARGO_TERM_COLOR = "always"
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600"
X-Frame-Options = "DENY"
Content-Security-Policy = "default-src 'self' 'unsafe-eval' 'wasm-unsafe-eval'"
Feature-Policy = "accelerometer 'none'; camera 'none'"

[context.production]
[context.production.environment]
DX_PROFILE = "release"
RUSTFLAGS = "-C opt-level=3"

[context.staging]
[context.staging.environment]
DX_PROFILE = "debug"
RUST_LOG = "debug"

[[headers]]
for = "/wasm/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Encoding = "br"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=604800"
